const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const TEAM_COLS=["Match Rank","Team ID","Team Name","Survival Score","Kill","Total Score","BOOYAH!","Damage","On Target","Headshots","Headshots Kill Rate","Headshot Accuracy Rate","Survival Time","Revival","Rescue Members"];
const PLAYER_COLS=["MatchRank","Team Name","Player ID","Player Name","Kill","Damage","Assistências","On Target","Moving Distance","Headshots","Headshot Kill Rate","Headshot Accuracy Rate","Revival","Revival Members","Knock Down","Rescue Members","Survival Time","Maximum Kill Distance"];
const state={match:null,saved:JSON.parse(localStorage.getItem('ffmi_matches')||'[]'),players:JSON.parse(localStorage.getItem('ffmi_players')||'{}'),aliases:JSON.parse(localStorage.getItem('ffmi_aliases')||'{}')};
function save(){localStorage.setItem('ffmi_matches',JSON.stringify(state.saved));localStorage.setItem('ffmi_players',JSON.stringify(state.players));localStorage.setItem('ffmi_aliases',JSON.stringify(state.aliases))}
function norm(s){return String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ')}
function shownPlayer(id,name){const p=state.players[String(id)];return p?.nick||name||''}
function teamName(name){const n=norm(name);return state.aliases[n]||name||''}
function renderTable(table,cols,rows){table.innerHTML='<thead><tr>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>`<td>${esc(r[c]??r[normalizeKey(c)]??'')}</td>`).join('')+'</tr>').join('')+'</tbody>'}
function normalizeKey(k){return String(k).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function transform(m){if(!m)return null;const teams=(m.teams||[]).map(t=>{const x={...t};x['Team Name']=teamName(x['Team Name']||x.teamName);return x});const players=(m.players||[]).map(p=>{const x={...p};x['Team Name']=teamName(x['Team Name']||x.teamName);x['Player Name']=shownPlayer(x['Player ID']||x.playerId,x['Player Name']||x.playerName);return x});return {...m,teams,players}}
function renderMatch(m){m=transform(m);state.match=m;$('#matchUrl').textContent=m.url||'';const live=!m.finalized;$('#liveBadge').classList.toggle('hidden',!live);$('#liveBadge').innerHTML=live?'<i></i> Partida Ao Vivo':'Partida Finalizada';const s=[['Modo',m.mode||'—'],['Formato',m.format||'—'],['Equipes',m.teamCount??m.teams?.length??0],['Players',m.playerCount??m.players?.length??0]];$('#summary').innerHTML=s.map(([a,b])=>`<div class="stat"><small>${a}</small><strong>${esc(b)}</strong></div>`).join('');renderTable($('#teamTable'),TEAM_COLS,m.teams||[]);renderTable($('#playerTable'),PLAYER_COLS,m.players||[]);$('#teamSection').classList.remove('hidden');$('#playerSection').classList.remove('hidden')}
async function fetchMatch(id,quiet=false){if(!quiet){$('#progress').classList.remove('hidden');$('#errorBox').classList.add('hidden');$('#progressText').textContent='Abrindo o MatchStats e procurando o botão View...'}try{const r=await fetch('/api/scrape?matchId='+encodeURIComponent(id));const data=await r.json();if(!r.ok)throw new Error(data.error||'Falha na extração');renderMatch(data);return data}catch(e){if(!quiet){$('#errorBox').textContent=e.message;$('#errorBox').classList.remove('hidden')}throw e}finally{if(!quiet)$('#progress').classList.add('hidden')}}
function replayId(s){const m=String(s).match(/^ReplayInfo_(\d+)_\d{4}(?:-|_)/i);return m?.[1]||null}
$('#searchBtn').onclick=async()=>{const id=replayId($('#replayInput').value)||$('#replayInput').value.trim();if(!id){$('#errorBox').textContent='Não consegui identificar o MatchID.';$('#errorBox').classList.remove('hidden');return}$('#matchUrl').textContent=`https://matchstats.us.ffesports.com/match?search=${id}`;await fetchMatch(id)};
$('#addCurrentMatch').onclick=()=>{if(!state.match)return;const id=state.match.matchId;if(!state.saved.includes(id))state.saved.push(id);save();renderSaved();alert('MatchID salvo.')};
async function loadSaved(){for(const id of state.saved){try{await fetchMatch(id,true)}catch{}}renderAggregate()}
function renderSaved(){$('#savedMatches').innerHTML=state.saved.map(id=>`<div class="match-tag">${esc(id)}<button data-id="${esc(id)}">×</button></div>`).join('')||'<span class="muted">Nenhuma partida salva.</span>';$$('#savedMatches button').forEach(b=>b.onclick=()=>{state.saved=state.saved.filter(x=>x!==b.dataset.id);save();renderSaved();renderAggregate()})}
function num(v){const n=Number(String(v??'').replace(',','.').replace(/[^\d.-]/g,''));return Number.isFinite(n)?n:0}
function aggregate(){const map=new Map();for(const m of state._loaded||[]){for(const row of m.teams||[]){const key=norm(row['Team Name']);if(!key)continue;if(!map.has(key))map.set(key,{...row,'Team Name':teamName(row['Team Name'])});else{const a=map.get(key);for(const c of TEAM_COLS){if(['Team Name','Match Rank','Team ID'].includes(c))continue;a[c]=num(a[c])+num(row[c])}}}}return [...map.values()]}
async function refreshAll(){state._loaded=[];for(const id of state.saved){try{const m=await fetchMatch(id,true);state._loaded.push(m)}catch{}}renderAggregate()}
function renderAggregate(){const rows=aggregate();renderTable($('#aggregateTable'),TEAM_COLS,rows)}
$('#addMatchBtn').onclick=async()=>{const id=$('#matchIdInput').value.trim();if(!id)return;if(!state.saved.includes(id))state.saved.push(id);save();renderSaved();$('#matchIdInput').value='';await refreshAll()};$('#refreshSaved').onclick=refreshAll;
$('#savePlayer').onclick=()=>{const id=$('#regId').value.trim();if(!id)return;state.players[id]={nick:$('#regNick').value.trim(),role:$('#regRole').value.trim()};save();renderRegistry();if(state.match)renderMatch(state.match)};
function renderRegistry(){const rows=Object.entries(state.players).map(([id,p])=>({'Player ID':id,'Nickname registrado':p.nick,'Função':p.role||''}));renderTable($('#registryTable'),['Player ID','Nickname registrado','Função'],rows)}
$('#saveTeam').onclick=()=>{const old=norm($('#oldTeam').value),neu=$('#newTeam').value.trim();if(!old||!neu)return;state.aliases[old]=neu;save();renderAliases();if(state.match)renderMatch(state.match);};function renderAliases(){$('#aliasList').innerHTML=Object.entries(state.aliases).map(([a,b])=>`<div class="alias-row"><span>${esc(a)}</span><strong>→ ${esc(b)}</strong></div>`).join('')||'<span>Nenhuma regra cadastrada.</span>'}
$$('.nav-item').forEach(b=>b.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active-view'));$('#'+b.dataset.view+'View').classList.add('active-view');$('#pageTitle').textContent=b.textContent});
renderSaved();renderRegistry();renderAliases();
setInterval(async()=>{if(state.match?.matchId){try{const m=await fetchMatch(state.match.matchId,true);if(m.finalized)$('#liveBadge').innerHTML='<i></i> Partida Finalizada'}catch{}}},1000);
