const TEAM_HEADERS=["Match Rank","Team ID","Team Name","Survival Score","Kill","Total Score","BOOYAH!","Damage","On Target","Headshots","Headshots Kill Rate","Headshot Accuracy Rate","Survival Time","Revival","Rescue Members"];
const PLAYER_HEADERS=["MatchRank","Team Name","Player ID","Player Name","Kill","Damage","Assistências","On Target","Moving Distance","Headshots","Headshot Kill Rate","Headshot Accuracy Rate","Revival","Revival Members","Knock Down","Rescue Members","Survival Time","Maximum Kill Distance"];
const $=s=>document.querySelector(s);
const state={current:null,players:JSON.parse(localStorage.getItem("ffmi_players")||"{}"),aliases:JSON.parse(localStorage.getItem("ffmi_aliases")||"{}"),matches:JSON.parse(localStorage.getItem("ffmi_matches")||"[]"),cache:JSON.parse(localStorage.getItem("ffmi_cache")||"{}"),poll:null};

function save(){localStorage.setItem("ffmi_players",JSON.stringify(state.players));localStorage.setItem("ffmi_aliases",JSON.stringify(state.aliases));localStorage.setItem("ffmi_matches",JSON.stringify(state.matches));localStorage.setItem("ffmi_cache",JSON.stringify(state.cache))}
function extractId(s){const m=String(s||"").match(/ReplayInfo[_-]([0-9]+)[_-](?:20\d{2})/i);return m?m[1]:(/^\d+$/.test(String(s).trim())?String(s).trim():"")}
function normalizeTeam(s){return String(s??"").trim().replace(/\s+/g," ").toLowerCase()}
function displayTeam(s){const k=normalizeTeam(s);return state.aliases[k]||String(s??"").trim()}
function setStatus(text,kind="idle"){$("#statusBadge").textContent=text;$("#statusBadge").className="status-badge "+kind}
function setTable(id,headers,rows){const t=$("#"+id);t.querySelector("thead").innerHTML="<tr>"+headers.map(h=>`<th>${esc(h)}</th>`).join("")+"</tr>";t.querySelector("tbody").innerHTML=rows.length?rows.map(r=>"<tr>"+headers.map((_,i)=>`<td>${esc(r[i]??"")}</td>`).join("")+"</tr>").join(""):`<tr><td class="empty" colspan="${headers.length}">Nenhum dado.</td></tr>`}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function applyPlayerRegistry(rows){return rows.map(r=>{const id=String(r[2]??"");const p=state.players[id];if(p)r[3]=p.nick;return r})}
function applyTeamAliases(rows){return rows.map(r=>{if(r.length>2)r[2]=displayTeam(r[2]);return r})}
function renderCurrent(data){state.current=data;$("#mode").textContent=data.mode||"—";$("#format").textContent=data.format||"—";$("#teamCount").textContent=data.teams?.length??"—";$("#playerCount").textContent=data.players?.length??"—";setTable("teamTable",TEAM_HEADERS,applyTeamAliases(data.teams||[]));setTable("playerTable",PLAYER_HEADERS,applyPlayerRegistry(applyTeamAliases(data.players||[])));const live=!data.finished;$("#liveBtn").textContent=live?"● Partida Ao Vivo":"● Partida Finalizada";$("#liveBtn").className="live-toggle "+(live?"":"finished");$("#lastUpdate").textContent="Atualizado em "+new Date().toLocaleTimeString("pt-BR");setStatus(live?"Partida Ao Vivo":"Partida Finalizada",live?"live":"idle");}
async function fetchMatch(id,silent=false){if(!id)return; if(!silent)setStatus("Consultando…","busy");$("#errorBox").classList.add("hidden");try{const r=await fetch(`/api/scrape?matchId=${encodeURIComponent(id)}`,{cache:"no-store"});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Não foi possível ler a partida.");state.cache[id]=d;save();renderCurrent(d)}catch(e){$("#errorBox").textContent=e.message;$("#errorBox").classList.remove("hidden");setStatus("Erro","idle")}}
function startPolling(){clearInterval(state.poll);if(!state.current?.matchId)return;state.poll=setInterval(()=>fetchMatch(state.current.matchId,true),5000)}
$("#replayInput").addEventListener("input",e=>{$("#matchIdPreview").textContent="MatchID: "+(extractId(e.target.value)||"—")});
$("#searchBtn").addEventListener("click",()=>{const id=extractId($("#replayInput").value);if(!id){$("#errorBox").textContent="Nome de ReplayInfo inválido.";$("#errorBox").classList.remove("hidden");return}fetchMatch(id).then(startPolling)});
$("#savePlayer").addEventListener("click",()=>{const id=$("#playerId").value.trim(),nick=$("#playerNick").value.trim(),role=$("#playerRole").value.trim();if(!id||!nick)return;state.players[id]={nick,role};save();renderRegistries();if(state.current)renderCurrent(state.current);$("#playerId").value=$("#playerNick").value=$("#playerRole").value=""});
$("#saveTeamAlias").addEventListener("click",()=>{const old=normalizeTeam($("#teamOld").value),nw=$("#teamNew").value.trim();if(!old||!nw)return;state.aliases[old]=nw;save();renderRegistries();if(state.current)renderCurrent(state.current)});
function renderRegistries(){$("#playerRegistry").innerHTML=Object.entries(state.players).map(([id,p])=>`<div class="registry-item"><div><b>${esc(p.nick)}</b><br><span>${esc(id)} · ${esc(p.role||"")}</span></div></div>`).join("")||'<span class="preview">Nenhum registro.</span>';$("#teamRegistry").innerHTML=Object.entries(state.aliases).map(([old,nw])=>`<div class="registry-item"><div><span>${esc(old)}</span> → <b>${esc(nw)}</b></div></div>`).join("")||'<span class="preview">Nenhum alias.</span>'}
$("#addMatchBtn").addEventListener("click",()=>{const id=$("#matchIdInput").value.trim();if(id&&!state.matches.includes(id)){state.matches.push(id);save();renderMatches();$("#matchIdInput").value="";}});
$("#addCurrentBtn").addEventListener("click",()=>{if(state.current?.matchId&&!state.matches.includes(state.current.matchId)){state.matches.push(state.current.matchId);save();renderMatches()}});
function renderMatches(){$("#savedMatches").innerHTML=state.matches.map(id=>`<div class="match-chip">${esc(id)}<button data-id="${esc(id)}">×</button></div>`).join("");document.querySelectorAll(".match-chip button").forEach(b=>b.onclick=()=>{state.matches=state.matches.filter(x=>x!==b.dataset.id);save();renderMatches();renderOverall()});renderOverall()}
async function renderOverall(){if(!state.matches.length){setTable("overallTable",TEAM_HEADERS,[]);return}const all=[];for(const id of state.matches){let d=state.cache[id];if(!d){try{const r=await fetch(`/api/scrape?matchId=${encodeURIComponent(id)}`,{cache:"no-store"});d=await r.json();if(d.ok){state.cache[id]=d;save()}}catch{}}if(d?.ok)all.push(...(d.teams||[]))}const map=new Map();for(const row of all){const key=normalizeTeam(row[2]);if(!map.has(key))map.set(key,row.slice());else{const a=map.get(key);for(let i=0;i<a.length;i++){if(i===2)continue;const x=parseFloat(String(a[i]).replace(",",".")),y=parseFloat(String(row[i]).replace(",","."));if(Number.isFinite(x)&&Number.isFinite(y))a[i]=String(x+y);else if(!a[i]&&row[i])a[i]=row[i]}}}const rows=[...map.values()].map(r=>{r[2]=displayTeam(r[2]);return r});setTable("overallTable",TEAM_HEADERS,rows)}
renderRegistries();renderMatches();
